namespace: t_systems_mms
name: mongodb_atlas
version: 0.3.2
readme: README.md
authors:
  - Martin Schurz <Martin.Schurz@t-systems.com>
description: >-
  This collection contains MongoDB Atlas modules to provision and automate the
  cloud offering of MongoDB via API.
license:
  - GPL-2.0-or-later
license_file: ''
tags:
  - mongodb
  - atlas
  - cloud
dependencies: {}
repository: 'https://github.com/T-Systems-MMS/ansible-collection-mongodb-atlas'
documentation: 'https://github.com/T-Systems-MMS/ansible-collection-mongodb-atlas'
homepage: 'https://github.com/T-Systems-MMS/ansible-collection-mongodb-atlas'
issues: 'https://github.com/T-Systems-MMS/ansible-collection-mongodb-atlas/issues'
build_ignore:
  - codecov.yml
  - .github
  - .gitattributes
  - .gitignore
  - hacking
  - requirements.txt
  - test-requirements.txt
  - tests
  - .tox
  - tox.ini
  - .yamllint
