---
name: New release

on:
  push:
jobs:
  update_docs:
    runs-on: ubuntu-latest
    name: create documentation inside docs-folder
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      # ansible-doc-extractor requires the collection to be in a directory in 
      # the form ~/.ansible/ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}/

      - name: Check out code to deafult ansible collection location
        uses: actions/checkout@v2.3.4
        with:
          path: /home/runner/.ansible/ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install ansible-doc-extractor
        run: python -m pip install ansible-doc-extractor[ansible]

      - name: create documentation
        run: ansible-doc-extractor docs/ plugins/modules/*

      - name: commit documentation
        uses: github-actions-x/commit@v2.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          commit-message: 'update documentation'
          force-add: 'true'
          files: docs/
          name: T-Systems MMS
          email: frage@t-systems-mms.com
