---
name: ansible-test

on:
  # Run CI against all pushes (direct commits, also merged PRs), Pull Requests
  push:
  pull_request:
  # Run CI once per week (at 06:00 UTC)
  # This ensures that even if there haven't been commits that we are still
  # testing against latest version of ansible-test for each ansible-core
  # version
  schedule:
    - cron: '0 6 * * 1'

env:
  NAMESPACE: t_systems_mms
  COLLECTION_NAME: mongodb_atlas

jobs:
  sanity:
    name: Sanity (Ⓐ${{ matrix.ansible }})
    strategy:
      matrix:
        ansible:
          - stable-2.11
          - stable-2.12
          - stable-2.13
          - devel
    runs-on: ubuntu-latest
    steps:

      # ansible-test requires the collection to be in a directory in the form
      # .../ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}/

      - name: Check out code
        uses: actions/checkout@v3
        with:
          path: ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # it is just required to run that once as "ansible-test sanity" in the docker image
          # will run on all python versions it supports.
          python-version: 3.9

      # Install the head of the given branch (devel, stable-2.10)
      - name: Install ansible-base (${{ matrix.ansible }})
        run: pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible }}.tar.gz --disable-pip-version-check

      # run ansible-test sanity inside of Docker.
      # The docker container has all the pinned dependencies that are required
      # and all python versions ansible supports.
      - name: Run sanity tests
        run: ansible-test sanity --docker -v --color
        working-directory: ./ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

  linting:
      name: Tox-Lint (py${{ matrix.python }})
      strategy:
        matrix:
          python:
            - "2.7"
            - "3.7"
            - "3.8"
            - "3.9"
            - "3.10"
      runs-on: ubuntu-latest
      steps:
        - name: Check out code
          uses: actions/checkout@v3
          with:
            path: ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

        - name: Set up Python ${{ matrix.python }}
          uses: actions/setup-python@v5
          with:
            python-version: ${{ matrix.python }}

        - name: Install dependencies
          run: python -m pip install flake8 tox

        - name: Run lint test
          run: tox -elinters -vv
          working-directory: ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}
