---
name: New release

on:
  push:
    branches:
      - master

env:
  NAMESPACE: t_systems_mms
  COLLECTION_NAME: mongodb_atlas
  ANSIBLE_COLLECTIONS_PATHS: ./

jobs:
  update_docs:
    runs-on: ubuntu-latest
    name: create documentation inside docs-folder
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # ansible-doc-extractor requires the collection to be in a directory in 
      # the form ./ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}/

      - name: Check out code to ansible collection location
        uses: actions/checkout@v3
        with:
          path: ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install ansible-doc-extractor
        run: python -m pip install ansible-doc-extractor[ansible]

      - name: create documentation
        run: ansible-doc-extractor docs/ plugins/modules/*

      - name: commit documentation
        uses: github-actions-x/commit@v2.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          commit-message: 'update documentation'
          force-add: 'true'
          files: docs/
          name: T-Systems MMS
          email: frage@t-systems-mms.com

  generate_changelog:
    runs-on: ubuntu-latest
    name: create release draft
    needs: update_docs  # the documentation should be updated before creating a new release
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@master"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: calculate next version
        id: version
        uses: patrickjahns/version-drafter-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate changelog
        uses: charmixer/auto-changelog-action@v1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          future_release: ${{ steps.version.outputs.next-version }}

      - name: push changelog
        uses: github-actions-x/commit@v2.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          commit-message: 'update changelog'
          force-add: 'true'
          files: CHANGELOG.md
          name: T-Systems MMS
          email: frage@t-systems-mms.com
          rebase: true

      # do a second checkout to prevent race situation
      # changelog gets updated but action works on old commit id
      - uses: actions/checkout@v3
        with:
          ref: master

      - name: Generate changelog for the release
        run: |
          sed '/## \[${{ steps.previoustag.outputs.tag }}\]/Q' CHANGELOG.md > CHANGELOGRELEASE.md

      - name: Read CHANGELOG.md
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./CHANGELOGRELEASE.md

      - name: Create Release draft
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # This token is provided by Actions, you do not need to create your own token
        with:
          release_name: ${{ steps.version.outputs.next-version }}
          tag_name: ${{ steps.version.outputs.next-version }}
          body: |
            ${{ steps.package.outputs.content }}
          draft: true
